### ISSUE TITLE
Use git submodules?

### ISSUE THREAD

**Issue by mxmilkb** [benkuper/Chataigne#44] opened 2019-11-17 19:21 UTC
This would make the build easier.

**Comment by benkuper** [comment] 2019-11-18 17:56
Yes that is a good idea, though I don't really like the idea of having a lot of different versions of organicui, timeline and juce on different folders of my computer, though I see the value of being able to link a specific commit of Chataigne to a specific commit of the differents modules and versions.
One thing is to be sure not to break the CI, which can take time to do well.
Would you be able to do a pull request for this ?

**Comment by mxmilkb** [comment] 2019-11-18 18:02
Adding submodules isn't hard, but what [commit they would point to](https://twoguysarguing.wordpress.com/2010/11/14/tie-git-submodules-to-a-particular-commit-or-branch/) would relate more to your requirements and understanding.

**Comment by benkuper** [comment] 2019-11-18 18:03
Yes I know it's not hard, I just have zero time to handle it right now

**Comment by mxmilkb** [comment] 2019-11-18 18:05
Sure thing, I'll PR in the next short while.

**Comment by benkuper** [comment] 2019-11-18 18:06
Thank you !
Most important is that all the CI (appveyor for win / travis for OSX-linux-raspberry) are still working !

**Comment by wraybowling** [comment] 2019-12-17 19:23
@benkuper As a more visual person, I like using Sourcetree instead of just git on the command line. As a result, managing things like submodules and subtrees feels much simpler to do. https://confluence.atlassian.com/sourcetreekb/adding-a-submodule-subtree-with-sourcetree-785332086.html

Literally just now learning about subtree linked from that knowledgebase article. Consider that as an option, too. https://www.atlassian.com/git/tutorials/git-subtree?_ga=2.52255529.1496751666.1576610224-237243916.1559843617

**Comment by benkuper** [comment] 2019-12-17 23:22
I'm personally using GitKraken :)
Subtree is interesting indeed, I'm not fully convinced by it though. I think submodules would be the standard way of doing it. The only thing I'm not happy about is that I had to modify JUCE's code in order to have the features needed, but most of my PR are just pending on the official repo, and I'm pretty confident that they won't be handled soon. So having to copy the fully JUCE git for every project using organicui seems a bit too much.. and not putting it as a submodule renders the whole process kind of incomplete and useless then..

**Comment by wraybowling** [comment] 2019-12-18 03:52
Submodules, like normal repos, can have multiple remotes. Use the commit on your fork, later switch out if the feature ever gets merged.

**Comment by benkuper** [comment] 2019-12-18 08:47
The issue is not really on the remote part, but on the local-copy part of the submodules. The JUCE folder is 3GB on my disk (some files left after compilation are taking space I guess) , and I don't wanna have to have a local copy of it in each project folder on my computer. If there was a way to have "external submodules", it would be great but I'm not sure about this one.

**Comment by benkuper** [comment] 2020-02-05 10:28
commit a1f9f762ac363edfdbd6cc92515915f192f2151e adds organicui and timeline as submodules

**Closed by benkuper** 2020-02-05 10:28 UTC
