### ISSUE TITLE
Ctrl+Q for quitting on Win & Linux

### ISSUE THREAD

**Issue by Adopo** [benkuper/Chataigne#20] opened 2018-03-14 13:32 UTC
Hello I have shown chataigne during a workshop with digital animator to give to us solution to control music.
One of the animateur have installed chataigne on linux 64 bit. It works fine but it had no command to close the software or minimize it.
The only way is to use alt+tab to navigate in another softwate or alt+f4 to quit.

**Comment by benkuper** [comment] 2018-03-15 16:14
Thanks for the feedback, the problem is actually accross all platforms, except on Mac, you do Command+Q instead of Alt+F4 to use the system's closing app feature.
There should still be a closing button on Linux, but i'll integrate the shortcut in the next version.

**Closed** 2018-03-15 18:57 UTC

**Comment by benkuper** [comment] 2018-03-15 18:58
https://github.com/benkuper/Chataigne/commit/7beb8bc20833fe3b273fd5ccb6bbe43bd0a44659

**Comment by Adopo** [comment] 2018-03-15 21:32
For information shortcut on linux are functionnal. On linux we can do alt+f4 for closing application ans alt+tab to change with an another. But impossible to go to the desktop.
Maybe if we have multi desktop is possible.
I dont know if this is functionnal on all linux

**Comment by benkuper** [comment] 2018-03-15 22:08
Yes, those shortcuts are handled by the system, i have added unified handling of the Command+Q shortcut. The minimizing should be the same as other softwares, with the window's buttons.
